### ISSUE TITLE
(1.2) kallellaan oleva ruutu

### ISSUE THREAD

**Issue by mluukkai** [ohjelmointikurssi/materiaali#2]
tehtävässä ei ole tarkastusta, tai se ei toimi

<img width="891" alt="tulostaminen" src="https://cloud.githubusercontent.com/assets/523235/18809000/ed0facea-8279-11e6-9fd8-343a174849bd.png">

**Comment by nygrenh** [comment]
Mulla ton tehtävän tarkastus toimii. Voitko laittaa mitä tulostuu konsoliin?

**Comment by mluukkai** [comment]
Laitan kun palaan tehtävien pariin. Huomasin juuri että olen tehnyt näitä väärällä selaimella (safari 9.1.2) eli syy voi olla siinä
